version: "3.9"

services:
  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  nextjs:
    build:
      context: ./nextjs
      dockerfile: Dockerfile
    volumes:
      - ./nextjs:/app
    ports:
      - "3000:3000"
    depends_on:
      - fastapi
    env_file:
      - .env

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./path_to_init.sql:/docker-entrypoint-initdb.d/init.sql

  psql:
    image: postgres:14
    command: psql -h db -U user -d mydb
    depends_on:
      - db
    stdin_open: true
    tty: true

volumes:
  postgres_data:
    driver: local
